# Load required libraries
library(shiny)
library(quarto)
library(dplyr)
library(readr)

# Load your data (ensure the filename matches your actual CSV)
# We do this outside the UI/Server so it only loads once
gait_data <- read_csv("Interpretation_Schedule.csv") %>%
  mutate(Date_of_Interp = as.character(Date_of_Interp)) # Ensure dates are strings for selection

ui <- fluidPage(
  titlePanel("EB GAIT Report Generator"),
  
  sidebarLayout(
    sidebarPanel(
      # Searchable MRN Input
      selectizeInput("MRN", "Search/Select MRN", 
                     choices = NULL, # Initialized as empty for performance
                     options = list(placeholder = 'Type to search...')),
      
      # This will be generated by the server based on the MRN chosen
      uiOutput("date_selector"),
      
      hr(),
      textInput("username", "User Name", "mschwartz@gillettechildrens.com"),
      passwordInput("password", "Password", "Duffy001!))))))))"),
      
      checkboxInput("deid", "Deidentify?", value = FALSE),
      checkboxInput("usevideo", "Include Video?", value = TRUE),
      checkboxInput("compare", "Compare Models?", value = TRUE),
      checkboxInput("figsave", "Save Figures?", value = FALSE),
      checkboxInput("usegait", "Use Gait Data?", value = TRUE),
      checkboxInput("custom_outcome", "Use Custom Outcome?", value = FALSE),
      
      actionButton("renderBtn", "Render EB GAIT Report", class = "btn-primary")
    ),
    
    mainPanel(
      verbatimTextOutput("status_log")
    )
  )
)

server <- function(input, output, session) {
  
  # Update the MRN choices on start
  updateSelectizeInput(session, "MRN", 
                       choices = unique(gait_data$MRN), 
                       server = TRUE)
  
  # Dynamically generate the Date dropdown based on selected MRN
  output$date_selector <- renderUI({
    req(input$MRN)
    
    # Filter dates available for the selected MRN
    available_dates <- gait_data %>%
      filter(MRN == input$MRN) %>%
      pull(Event_Date)
    
    selectInput("Event_Date", "Event Date", choices = available_dates)
  })
  
  # Function to render Quarto document
  renderQuarto <- function() {
    req(input$MRN, input$Event_Date)
    
    # 1. Ensure the output directory exists
    if (!dir.exists("REPORTS")) {
      dir.create("REPORTS")
    }
    
    # 2. Set up parameters for the main report
    EBReport_params <- list(
      MRN = input$MRN,
      Event_Date = input$Event_Date,
      deid = input$deid,
      usevideo = input$usevideo,
      figsave = input$figsave,
      usegait = input$usegait,
      custom_outcome = input$custom_outcome,
      username = input$username,
      password = input$password
    )
    
    # Define filenames
    # Quarto requires 'output_file' to be a simple name, NO paths
    temp_main <- paste0("temp_main_", input$MRN, ".html")
    final_main <- glue::glue("REPORTS/EBReport_{input$MRN}_{input$Event_Date}.html")
    
    showNotification(paste("Rendering main report for MRN:", input$MRN), type = "message")
    
    # 3. Render the main report
    quarto::quarto_render(
      input = "EBReport.qmd",
      execute_params = EBReport_params,
      output_file = temp_main
    )
    
    # 4. Move to final destination
    if (file.exists(temp_main)) {
      file.rename(temp_main, final_main)
    }
    
    # 5. Handle Comparison Report if checkbox is checked
    if (input$compare) {
      EBCompare_params <- list(
        MRN = input$MRN,
        Event_Date = input$Event_Date,
        fit_prop = FALSE,
        fit_out = FALSE
      )
      
      temp_comp <- paste0("temp_comp_", input$MRN, ".html")
      final_comp <- glue::glue("REPORTS/EBCompare_{input$MRN}_{input$Event_Date}.html")
      
      showNotification("Rendering Comparison Report...", type = "message")
      
      quarto::quarto_render(
        input = "EBCompare.qmd",
        execute_params = EBCompare_params,
        output_file = temp_comp
      )
      
      if (file.exists(temp_comp)) {
        file.rename(temp_comp, final_comp)
      }
    }
    
    showNotification("All Rendering Complete!", type = "message")
  }
  
  observeEvent(input$renderBtn, { renderQuarto() })
}

shinyApp(ui, server)